apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-application
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/your-username/my-gitops-repo'
    path: postgres
  project: default
